import type * as OpenPgp from 'openpgp';

type OpenPgpModule = typeof OpenPgp;

/**
 * `openpgp` is loaded on first use, the way `mkcertProvenance.ts` loads
 * Sigstore, not imported at the top: a missing or broken package must fail the
 * dependency update that needs it (closed, like every other check here), not
 * the server's boot. A failed load is not cached, so a repaired install works
 * without a restart.
 */
let openpgpModule: Promise<OpenPgpModule> | undefined;

function loadOpenPgp(): Promise<OpenPgpModule> {
    if (!openpgpModule) {
        const loading = import('openpgp');
        openpgpModule = loading;
        loading.catch(() => {
            if (openpgpModule === loading) openpgpModule = undefined;
        });
    }
    return openpgpModule;
}

/**
 * M5: a publisher's OpenPGP key, pinned in this repo. The pinned sets live in
 * `release-keys/pinnedReleaseKeys.ts`, generated by
 * `scripts/refresh-release-keys.mjs`; tests build their own sets from a
 * throwaway key and hand them to `DependencyManager` through its constructor.
 */
export interface PinnedKey {
    /** The PRIMARY key's v4 fingerprint, 40 upper-case hex digits. */
    readonly fingerprint: string;
    /** Who the publisher says holds it, for log lines and error messages. */
    readonly owner: string;
    /** The armored public key block (it may carry signing subkeys). */
    readonly armored: string;
}

/** The keys allowed to sign one publisher's hash lists, and the name errors use for that publisher. */
export interface ReleaseKeySet {
    /** e.g. `Node.js`: read as "not a pinned Node.js release key". */
    readonly label: string;
    readonly keys: readonly PinnedKey[];
}

/**
 * Why a signature check refused. Every one of them refuses the install; the
 * distinction is only for the message, which is what a user pastes into a bug
 * report.
 */
export type SignatureFailure = 'missing-signature' | 'bad-signature' | 'unknown-key' | 'key-not-valid';

export class ReleaseSignatureError extends Error {
    constructor(
        readonly reason: SignatureFailure,
        message: string,
    ) {
        super(message);
        this.name = 'ReleaseSignatureError';
    }
}

export interface VerifiedSignature {
    /** The pinned PRIMARY key's fingerprint. */
    fingerprint: string;
    /** The fingerprint of the key that actually signed: the primary, or one of its subkeys. */
    signingKeyFingerprint: string;
    owner: string;
    created: Date;
}

const REFUSE = '-- refusing to install';

interface ParsedKey {
    pinned: PinnedKey;
    key: OpenPgp.PublicKey;
}

/**
 * Parsed once per set. A pinned entry whose armored block does not parse, is a
 * PRIVATE key, or carries a different fingerprint than the one recorded beside
 * it is a broken pin, and every verification against that set throws.
 */
const parsedSets = new WeakMap<ReleaseKeySet, Promise<ParsedKey[]>>();

function parseKeySet(openpgp: OpenPgpModule, set: ReleaseKeySet): Promise<ParsedKey[]> {
    let parsed = parsedSets.get(set);
    if (!parsed) {
        parsed = Promise.all(
            set.keys.map(async (pinned) => {
                const key = await openpgp.readKey({ armoredKey: pinned.armored });
                if (key.isPrivate()) {
                    throw new Error(`pinned ${set.label} key ${pinned.fingerprint} is a private key`);
                }
                const actual = key.getFingerprint().toUpperCase();
                if (actual !== pinned.fingerprint.toUpperCase()) {
                    throw new Error(
                        `pinned ${set.label} key ${pinned.fingerprint} parses as ${actual} -- the pinned set is corrupt`,
                    );
                }
                return { pinned, key: key as OpenPgp.PublicKey };
            }),
        );
        // A failed parse is not cached: the next call reports it again rather
        // than replaying a rejected promise forever.
        parsed.catch(() => parsedSets.delete(set));
        parsedSets.set(set, parsed);
    }
    return parsed;
}

const ARMOR_HEADER = '-----BEGIN PGP SIGNATURE-----';

async function readDetachedSignature(openpgp: OpenPgpModule, bytes: Uint8Array): Promise<OpenPgp.Signature> {
    const text = new TextDecoder('utf-8', { fatal: false }).decode(bytes);
    if (text.trimStart().startsWith(ARMOR_HEADER)) {
        return openpgp.readSignature({ armoredSignature: text });
    }
    return openpgp.readSignature({ binarySignature: bytes });
}

function hex(bytes: Uint8Array): string {
    return Buffer.from(bytes).toString('hex').toUpperCase();
}

/**
 * The issuer the packet CLAIMS, as specifically as it names it: the full
 * fingerprint when present, else the key ID. Only a verified signature
 * authenticates its issuer, and these are read before anything is verified,
 * so messages call this the "claimed issuer".
 */
function claimedIssuerOf(packet: OpenPgp.SignaturePacket): string {
    const fpr = packet.issuerFingerprint;
    if (fpr instanceof Uint8Array && fpr.length > 0) return hex(fpr);
    return `key ID ${packet.issuerKeyID.toHex().toUpperCase()}`;
}

/**
 * The all-zero wildcard key ID, or none at all: either way the packet names no
 * key. (openpgp has `isWildcard()`, but its typings omit it.)
 */
function isWildcard(keyID: OpenPgp.KeyID): boolean {
    return /^0*$/.test(keyID.toHex());
}

/**
 * The pinned key holding the key (primary or subkey) whose ID the packet names,
 * compared EXACTLY. openpgp's own `getKeys(keyID)` treats the all-zero wildcard
 * ID as matching every key, so it would hand an anonymous signature to the
 * first pinned key and report the stranger's signature as merely bad.
 */
function pinnedSignerOf(keys: readonly ParsedKey[], packet: OpenPgp.SignaturePacket): ParsedKey | undefined {
    if (isWildcard(packet.issuerKeyID)) return undefined;
    return keys.find((k) => k.key.getKeyIDs().some((id) => id.equals(packet.issuerKeyID)));
}

/**
 * `SignaturePacket.verify` with no date runs every check except the two about
 * time (made in the future, expired); its typings do not admit the `null`.
 */
const AT_NO_PARTICULAR_TIME = null as unknown as Date;

/** The creation times of those `checks` (one per signature) that pass. */
async function madeAt(checks: readonly { signature: OpenPgp.SignaturePacket; check: () => Promise<void> }[]) {
    const times = await Promise.all(
        checks.map(({ signature, check }) =>
            check().then(
                () => signature.created,
                () => null,
            ),
        ),
    );
    return times.filter((d): d is Date => d instanceof Date);
}

/**
 * How `valueAt` judged a key that signed at `created`:
 *   - `then`     at `created`: a self-signature (or binding) that verifies was
 *                made at or before the signature, so the key is judged as it
 *                stood then, exactly as openpgp judges it;
 *   - `expired`  likewise, but nothing was valid at `created` -- what was made
 *                by then had expired by then (or, for a self-signature, its
 *                user ID was revoked). It is NOT judged again from a later
 *                one: a renewal does not reach back over a lapse;
 *   - `renewed`  every one that verifies was made AFTER the signature, so the
 *                key is judged from the NEWEST of them that is valid when it
 *                was made, the way GnuPG judges a key by its newest
 *                self-signature;
 *   - `none`     nothing verifies at all.
 */
type Judged<T> =
    | { how: 'then'; at: Date; value: T }
    | { how: 'renewed'; at: Date; value: T }
    | { how: 'expired' }
    | { how: 'none' };

async function judgedAtSigning<T>(
    created: Date,
    made: readonly Date[],
    valueAt: (at: Date) => Promise<T>,
): Promise<Judged<T>> {
    if (made.some((d) => d <= created)) {
        try {
            return { how: 'then', at: created, value: await valueAt(created) };
        } catch {
            return { how: 'expired' };
        }
    }
    const newestFirst = [...new Set(made.map((d) => d.getTime()))].sort((a, b) => b - a);
    for (const time of newestFirst) {
        const at = new Date(time);
        try {
            return { how: 'renewed', at, value: await valueAt(at) };
        } catch {
            // Not valid when it was made (a revoked user ID, say); try the next newest.
        }
    }
    return { how: 'none' };
}

/** The newest of `signatures` that `check` accepts, as openpgp picks a self-signature or binding. */
async function latestValid(
    signatures: readonly OpenPgp.SignaturePacket[],
    check: (signature: OpenPgp.SignaturePacket) => Promise<void>,
): Promise<OpenPgp.SignaturePacket> {
    let latest: OpenPgp.SignaturePacket | undefined;
    for (const signature of signatures) {
        try {
            await check(signature);
        } catch {
            continue;
        }
        if (!latest || signature.created! >= latest.created!) latest = signature;
    }
    if (!latest) throw new Error('no valid signature');
    return latest;
}

/** Whether the key expiry `signature` sets for `keyPacket` had passed by `date` (openpgp's own arithmetic). */
function expiredBy(keyPacket: OpenPgp.AnyKeyPacket, signature: OpenPgp.SignaturePacket, date: Date): boolean {
    if (signature.keyNeverExpires !== false) return false;
    const expiry = keyPacket.created.getTime() + (signature.keyExpirationTime ?? 0) * 1000;
    return expiry !== 0 && date.getTime() >= expiry;
}

/** openpgp's `validateSigningKeyPacket`: a signing algorithm, and key flags that allow signing. */
function maySign(openpgp: OpenPgpModule, keyPacket: OpenPgp.AnyKeyPacket, signature: OpenPgp.SignaturePacket): boolean {
    const { publicKey } = openpgp.enums;
    const signing = [
        publicKey.rsaEncryptSign,
        publicKey.rsaSign,
        publicKey.dsa,
        publicKey.ecdsa,
        publicKey.eddsaLegacy,
        publicKey.ed25519,
        publicKey.ed448,
    ];
    if (!signing.includes(keyPacket.algorithm)) return false;
    if (!signature.keyFlags) return openpgp.config.allowMissingKeyFlags;
    return (signature.keyFlags[0]! & openpgp.enums.keyFlags.signData) !== 0;
}

/** openpgp's `checkKeyRequirements`: why the key is too weak for its config, or null. */
function weakKey(openpgp: OpenPgpModule, keyPacket: OpenPgp.AnyKeyPacket): string | null {
    const { config, enums } = openpgp;
    const info = keyPacket.getAlgorithmInfo();
    if (config.rejectPublicKeyAlgorithms.has(keyPacket.algorithm))
        return `${info.algorithm} keys are considered too weak`;
    switch (keyPacket.algorithm) {
        case enums.publicKey.rsaEncryptSign:
        case enums.publicKey.rsaSign:
        case enums.publicKey.rsaEncrypt:
            return (info.bits ?? 0) < config.minRSABits
                ? `RSA keys shorter than ${config.minRSABits} bits are considered too weak`
                : null;
        case enums.publicKey.ecdsa:
        case enums.publicKey.eddsaLegacy:
        case enums.publicKey.ecdh:
            return info.curve && config.rejectCurves.has(info.curve as unknown as OpenPgp.enums.curve)
                ? `${info.algorithm} keys using curve ${info.curve} are disabled`
                : null;
        default:
            return null;
    }
}

/**
 * The key-renewal policy (user decision, 2026-10-07): accept a signature the
 * way GnuPG does when the pinned key was re-self-signed AFTER it was made.
 *
 * openpgp 6 judges a key at the signature's creation time using only the
 * self-signatures and subkey bindings that existed then. Publishers renew
 * their keys -- a new self-signature, usually to move the expiry -- and the key
 * they publish keeps only the newest, so everything signed before the renewal
 * is refused as "Signature creation time is in the future". In October 2026
 * that was 53 of the 163 Node.js releases from v20.0.0 on.
 *
 * This runs only after openpgp's strict check refused and the packet has
 * verified over the exact bytes on its own. Which self-signature (and, for a
 * subkey, which binding) it judges the key from:
 *   - when one that verifies was made at or before the signature, the key is
 *     judged at the signing time and ONLY then, from the newest one valid then
 *     -- exactly what openpgp judges by. If none is valid then (it had expired:
 *     openpgp counts a self-signature's own expiry as the key's), the
 *     signature is refused, however the key was renewed later;
 *   - only when every one that verifies was made AFTER the signature -- a
 *     renewed key published with nothing but its new self-signatures -- is it
 *     judged from the NEWEST of them, as GnuPG judges a key by its newest
 *     self-signature and binding. (Measured with GnuPG 2.4.9 on keys whose
 *     two post-dated self-signatures, or bindings, disagree on the signing
 *     flag or the key expiry: it followed the newer one every time.)
 * Every check below must pass:
 *   - existed     the primary key, and the signing subkey, were created at or
 *                 before the signature;
 *   - not revoked no revocation of the primary key or the subkey was in force
 *                 at the signing time: a hard one (compromise, or no reason)
 *                 counts whenever it was made, as openpgp counts it, a soft one
 *                 (retired, superseded) only if it was made by then;
 *   - not expired the key expiry that self-signature, or binding, sets falls
 *                 after the signature;
 *   - may sign    for the primary key, that self-signature's key flags; for a
 *                 subkey, a valid binding signature (made at any date) with the
 *                 signing flag and a valid back-signature;
 *   - not weak    openpgp's own key requirements (rejected algorithms and
 *                 curves, minimum RSA size).
 * A key with direct-key signatures is not judged here (none of the pinned keys
 * has one), so it is refused as openpgp refused it.
 *
 * Returns why the key was not valid when it signed, or null when it was.
 */
async function whyKeyWasNotValidAt(
    openpgp: OpenPgpModule,
    key: OpenPgp.PublicKey,
    signingKey: OpenPgp.PublicKey | OpenPgp.Subkey,
    created: Date,
): Promise<string | null> {
    const { config, enums } = openpgp;
    const primary = key.keyPacket;
    const subkey = signingKey === key ? null : (signingKey as OpenPgp.Subkey);

    if (primary.created > created || signingKey.getCreationTime() > created) {
        return 'the key did not exist yet';
    }

    // `isRevoked` with no signature asks about the key itself, at `created`.
    if (await key.isRevoked(undefined, undefined, created, config)) return 'the primary key is revoked';
    const anySignature = undefined as unknown as OpenPgp.SignaturePacket;
    if (subkey && (await subkey.isRevoked(anySignature, primary, created, config))) {
        return 'the signing subkey is revoked';
    }

    if (primary.version !== 4 || ((key as { directSignatures?: unknown[] }).directSignatures ?? []).length > 0) {
        return 'renewal is judged only for v4 keys without direct-key signatures';
    }
    // Only the user IDs getPrimaryUser considers (a user attribute has no user ID).
    const selfCertified = await madeAt(
        key.users.flatMap((u) =>
            u.userID
                ? u.selfCertifications.map((signature) => ({
                      signature,
                      check: () =>
                          signature.verify(
                              primary,
                              enums.signature.certGeneric,
                              { userID: u.userID, key: primary },
                              AT_NO_PARTICULAR_TIME,
                              undefined,
                              config,
                          ),
                  }))
                : [],
        ),
    );
    const self = await judgedAtSigning(
        created,
        selfCertified,
        async (at) => (await key.getPrimaryUser(at, undefined, config)).selfCertification,
    );
    if (self.how === 'none') return 'it carries no valid self-signature';
    if (self.how === 'expired') return 'its self-signature had expired by then, or its user ID was revoked';
    const selfSignature = self.value;
    if (expiredBy(primary, selfSignature, created)) return 'the key had expired by then';

    if (subkey) {
        const bound = { key: primary, bind: subkey.keyPacket };
        const verifyBinding = (s: OpenPgp.SignaturePacket, at: Date) =>
            s.verify(primary, enums.signature.subkeyBinding, bound, at, undefined, config);
        const found = await judgedAtSigning(
            created,
            await madeAt(
                subkey.bindingSignatures.map((signature) => ({
                    signature,
                    check: () => verifyBinding(signature, AT_NO_PARTICULAR_TIME),
                })),
            ),
            (at) => latestValid(subkey.bindingSignatures, (s) => verifyBinding(s, at)),
        );
        if (found.how === 'none') return 'it carries no valid subkey binding signature';
        if (found.how === 'expired') return 'its subkey binding signature had expired by then';
        const { at, value: binding } = found;
        if (!maySign(openpgp, subkey.keyPacket, binding)) return 'its subkey binding signature does not allow signing';
        // The subkey's own back-signature, so a subkey cannot be claimed by a primary key it never agreed to.
        const back = binding.embeddedSignature;
        const backValid =
            back !== null &&
            (await back.verify(subkey.keyPacket, enums.signature.keyBinding, bound, at, undefined, config).then(
                () => true,
                () => false,
            ));
        if (!backValid) return 'its subkey binding signature has no valid back-signature';
        if (expiredBy(subkey.keyPacket, binding, created)) return 'the signing subkey had expired by then';
    } else if (!maySign(openpgp, primary, selfSignature)) {
        return 'its self-signature does not allow signing';
    }

    return weakKey(openpgp, primary) ?? weakKey(openpgp, signingKey.keyPacket);
}

/**
 * Verifies a DETACHED signature (binary `.sig` or armored `.asc`) over the
 * exact bytes of `data` against one publisher's pinned keys.
 *
 * Returns the signer. Throws `ReleaseSignatureError` for:
 *   - bad-signature  the signature does not parse, holds no signature packet,
 *                    holds a packet that is not a signature, or does not
 *                    verify over these bytes;
 *   - unknown-key    a signature packet's claimed issuer is outside the pinned
 *                    set (the message carries the fingerprint or key ID it
 *                    claims, which nothing has authenticated), or it names no
 *                    issuer at all (the all-zero wildcard key ID);
 *   - key-not-valid  the pinned key was not valid when the signature says it
 *                    was made (expired, revoked, or not yet created then).
 *
 * A key that has EXPIRED SINCE is fine: the key is judged at the signature's
 * creation time, which is what lets a retired Node.js releaser's key still
 * vouch for the releases it signed. So is a key RENEWED since, whose
 * self-signature is newer than the signature: see `whyKeyWasNotValidAt`.
 * (`missing-signature` is raised by the caller, which is the one that knows
 * the file was not there.)
 *
 * Every signature packet must pass, not just one, so a file carrying a good
 * signature beside one by an unpinned key is refused rather than half-trusted.
 *
 * `openpgp` is loaded here, on first use; if it cannot be, the check throws
 * and the install is refused like any other failed check.
 */
export async function verifyDetachedSignature(args: {
    /** What was signed, for messages: `Node.js SHASUMS256.txt for v24.21.0`. */
    what: string;
    data: Uint8Array;
    signature: Uint8Array;
    keySet: ReleaseKeySet;
}): Promise<VerifiedSignature> {
    const { what, data, keySet } = args;
    const bad = (why: string) =>
        new ReleaseSignatureError('bad-signature', `${what}: signature does not verify (${why}) ${REFUSE}`);

    let openpgp: OpenPgpModule;
    try {
        openpgp = await loadOpenPgp();
    } catch (err) {
        throw new Error(
            `${what}: the OpenPGP library could not be loaded (${(err as Error).message}) -- refusing to install an unverified list`,
        );
    }

    let signature: OpenPgp.Signature;
    try {
        signature = await readDetachedSignature(openpgp, args.signature);
    } catch (err) {
        throw bad(`unreadable: ${(err as Error).message}`);
    }
    const packets = signature.packets.filter((p): p is OpenPgp.SignaturePacket => p instanceof openpgp.SignaturePacket);
    // A packet openpgp kept but could not parse as a signature (an unsupported
    // version, say) is skipped by its verify(); refuse the file rather than let
    // a good signature beside it carry it.
    if (packets.length !== signature.packets.length) {
        throw bad('a packet that is not a signature');
    }
    if (packets.length === 0) {
        throw bad('no signature packet');
    }

    const keys = await parseKeySet(openpgp, keySet);
    const signers = packets.map((packet) => {
        const signer = pinnedSignerOf(keys, packet);
        if (signer) return signer;
        if (isWildcard(packet.issuerKeyID)) {
            const fpr = packet.issuerFingerprint;
            throw new ReleaseSignatureError(
                'unknown-key',
                `${what} names no issuer key (wildcard key ID${
                    fpr instanceof Uint8Array && fpr.length > 0 ? `; claimed issuer fingerprint ${hex(fpr)}` : ''
                }), so no pinned ${keySet.label} release key can be matched to it ${REFUSE}`,
            );
        }
        throw new ReleaseSignatureError(
            'unknown-key',
            `${what} names ${claimedIssuerOf(packet)} as its claimed issuer, which is not a pinned ${keySet.label} release key ${REFUSE}`,
        );
    });

    const message = await openpgp.createMessage({ binary: data });
    const result = await openpgp.verify({
        message,
        signature,
        verificationKeys: signers.map((s) => s.key),
        format: 'binary',
    });
    // openpgp drops signature types other than binary/text; a packet it
    // dropped was not checked, so it does not count as passing.
    if (result.signatures.length !== packets.length) {
        throw bad('a signature packet is not a document signature');
    }
    const literal = message.packets.find((p): p is OpenPgp.LiteralDataPacket => p instanceof openpgp.LiteralDataPacket);
    if (!literal) throw bad('no literal data to check against');

    let first: VerifiedSignature | undefined;
    // Each signer below is matched on an exact, non-wildcard key ID, so
    // `getKeys` with that ID finds exactly that key.
    for (const [i, packet] of packets.entries()) {
        const signer = signers[i]!;
        const created = packet.created;
        if (!(created instanceof Date)) throw bad('the signature has no creation time');
        const signingKey = signer.key.getKeys(packet.issuerKeyID)[0]!;
        try {
            await result.signatures[i]!.verified;
        } catch {
            // openpgp's strict check refused: the bytes, or the key as its
            // self-signatures stood at the signing time. Decide it again under
            // the key-renewal policy below, which asks the two questions apart.
            try {
                await packet.verify(
                    signingKey.keyPacket,
                    packet.signatureType!,
                    literal,
                    new Date(),
                    true,
                    openpgp.config,
                );
            } catch (err) {
                throw bad((err as Error).message);
            }
            const why = await whyKeyWasNotValidAt(openpgp, signer.key, signingKey, created);
            if (why) {
                throw new ReleaseSignatureError(
                    'key-not-valid',
                    `${what} was signed on ${created.toISOString()} by ${signer.pinned.fingerprint} ` +
                        `(${signer.pinned.owner}), a key that was not valid then (${why}) ${REFUSE}`,
                );
            }
        }
        first ??= {
            fingerprint: signer.pinned.fingerprint.toUpperCase(),
            signingKeyFingerprint: signingKey.getFingerprint().toUpperCase(),
            owner: signer.pinned.owner,
            created,
        };
    }
    return first!;
}
