import type * as OpenPgp from 'openpgp';

type OpenPgpModule = typeof OpenPgp;

/**
 * `openpgp` is loaded on first use, the way `mkcertProvenance.ts` loads
 * Sigstore, not imported at the top: a missing or broken package must fail the
 * dependency update that needs it (closed, like every other check here), not
 * the server's boot. A failed load is not cached, so a repaired install works
 * without a restart.
 */
let openpgpModule: Promise<OpenPgpModule> | undefined;

function loadOpenPgp(): Promise<OpenPgpModule> {
    if (!openpgpModule) {
        const loading = import('openpgp');
        openpgpModule = loading;
        loading.catch(() => {
            if (openpgpModule === loading) openpgpModule = undefined;
        });
    }
    return openpgpModule;
}

/**
 * M5: a publisher's OpenPGP key, pinned in this repo. The pinned sets live in
 * `release-keys/pinnedReleaseKeys.ts`, generated by
 * `scripts/refresh-release-keys.mjs`; tests build their own sets from a
 * throwaway key and hand them to `DependencyManager` through its constructor.
 */
export interface PinnedKey {
    /** The PRIMARY key's v4 fingerprint, 40 upper-case hex digits. */
    readonly fingerprint: string;
    /** Who the publisher says holds it, for log lines and error messages. */
    readonly owner: string;
    /** The armored public key block (it may carry signing subkeys). */
    readonly armored: string;
}

/** The keys allowed to sign one publisher's hash lists, and the name errors use for that publisher. */
export interface ReleaseKeySet {
    /** e.g. `Node.js`: read as "not a pinned Node.js release key". */
    readonly label: string;
    readonly keys: readonly PinnedKey[];
}

/**
 * Why a signature check refused. Every one of them refuses the install; the
 * distinction is only for the message, which is what a user pastes into a bug
 * report.
 */
export type SignatureFailure = 'missing-signature' | 'bad-signature' | 'unknown-key' | 'key-not-valid';

export class ReleaseSignatureError extends Error {
    constructor(
        readonly reason: SignatureFailure,
        message: string,
    ) {
        super(message);
        this.name = 'ReleaseSignatureError';
    }
}

export interface VerifiedSignature {
    /** The pinned PRIMARY key's fingerprint. */
    fingerprint: string;
    /** The fingerprint of the key that actually signed: the primary, or one of its subkeys. */
    signingKeyFingerprint: string;
    owner: string;
    created: Date;
}

const REFUSE = '-- refusing to install';

interface ParsedKey {
    pinned: PinnedKey;
    key: OpenPgp.PublicKey;
}

/**
 * Parsed once per set. A pinned entry whose armored block does not parse, is a
 * PRIVATE key, or carries a different fingerprint than the one recorded beside
 * it is a broken pin, and every verification against that set throws.
 */
const parsedSets = new WeakMap<ReleaseKeySet, Promise<ParsedKey[]>>();

function parseKeySet(openpgp: OpenPgpModule, set: ReleaseKeySet): Promise<ParsedKey[]> {
    let parsed = parsedSets.get(set);
    if (!parsed) {
        parsed = Promise.all(
            set.keys.map(async (pinned) => {
                const key = await openpgp.readKey({ armoredKey: pinned.armored });
                if (key.isPrivate()) {
                    throw new Error(`pinned ${set.label} key ${pinned.fingerprint} is a private key`);
                }
                const actual = key.getFingerprint().toUpperCase();
                if (actual !== pinned.fingerprint.toUpperCase()) {
                    throw new Error(
                        `pinned ${set.label} key ${pinned.fingerprint} parses as ${actual} -- the pinned set is corrupt`,
                    );
                }
                return { pinned, key: key as OpenPgp.PublicKey };
            }),
        );
        // A failed parse is not cached: the next call reports it again rather
        // than replaying a rejected promise forever.
        parsed.catch(() => parsedSets.delete(set));
        parsedSets.set(set, parsed);
    }
    return parsed;
}

const ARMOR_HEADER = '-----BEGIN PGP SIGNATURE-----';

async function readDetachedSignature(openpgp: OpenPgpModule, bytes: Uint8Array): Promise<OpenPgp.Signature> {
    const text = new TextDecoder('utf-8', { fatal: false }).decode(bytes);
    if (text.trimStart().startsWith(ARMOR_HEADER)) {
        return openpgp.readSignature({ armoredSignature: text });
    }
    return openpgp.readSignature({ binarySignature: bytes });
}

function hex(bytes: Uint8Array): string {
    return Buffer.from(bytes).toString('hex').toUpperCase();
}

/**
 * The issuer the packet CLAIMS, as specifically as it names it: the full
 * fingerprint when present, else the key ID. Only a verified signature
 * authenticates its issuer, and these are read before anything is verified,
 * so messages call this the "claimed issuer".
 */
function claimedIssuerOf(packet: OpenPgp.SignaturePacket): string {
    const fpr = packet.issuerFingerprint;
    if (fpr instanceof Uint8Array && fpr.length > 0) return hex(fpr);
    return `key ID ${packet.issuerKeyID.toHex().toUpperCase()}`;
}

/**
 * The all-zero wildcard key ID, or none at all: either way the packet names no
 * key. (openpgp has `isWildcard()`, but its typings omit it.)
 */
function isWildcard(keyID: OpenPgp.KeyID): boolean {
    return /^0*$/.test(keyID.toHex());
}

/**
 * The pinned key holding the key (primary or subkey) whose ID the packet names,
 * compared EXACTLY. openpgp's own `getKeys(keyID)` treats the all-zero wildcard
 * ID as matching every key, so it would hand an anonymous signature to the
 * first pinned key and report the stranger's signature as merely bad.
 */
function pinnedSignerOf(keys: readonly ParsedKey[], packet: OpenPgp.SignaturePacket): ParsedKey | undefined {
    if (isWildcard(packet.issuerKeyID)) return undefined;
    return keys.find((k) => k.key.getKeyIDs().some((id) => id.equals(packet.issuerKeyID)));
}

/**
 * Verifies a DETACHED signature (binary `.sig` or armored `.asc`) over the
 * exact bytes of `data` against one publisher's pinned keys.
 *
 * Returns the signer. Throws `ReleaseSignatureError` for:
 *   - bad-signature  the signature does not parse, holds no signature packet,
 *                    or does not verify over these bytes;
 *   - unknown-key    a signature packet's claimed issuer is outside the pinned
 *                    set (the message carries the fingerprint or key ID it
 *                    claims, which nothing has authenticated), or it names no
 *                    issuer at all (the all-zero wildcard key ID);
 *   - key-not-valid  the pinned key was not valid when the signature says it
 *                    was made (expired, revoked, or not yet created then).
 *
 * A key that has EXPIRED SINCE is fine: openpgp checks the key at the
 * signature's creation time, which is what lets a retired Node.js releaser's
 * key still vouch for the releases it signed. (`missing-signature` is raised
 * by the caller, which is the one that knows the file was not there.)
 *
 * Every signature packet must pass, not just one, so a file carrying a good
 * signature beside one by an unpinned key is refused rather than half-trusted.
 *
 * `openpgp` is loaded here, on first use; if it cannot be, the check throws
 * and the install is refused like any other failed check.
 */
export async function verifyDetachedSignature(args: {
    /** What was signed, for messages: `Node.js SHASUMS256.txt for v24.21.0`. */
    what: string;
    data: Uint8Array;
    signature: Uint8Array;
    keySet: ReleaseKeySet;
}): Promise<VerifiedSignature> {
    const { what, data, keySet } = args;
    const bad = (why: string) =>
        new ReleaseSignatureError('bad-signature', `${what}: signature does not verify (${why}) ${REFUSE}`);

    let openpgp: OpenPgpModule;
    try {
        openpgp = await loadOpenPgp();
    } catch (err) {
        throw new Error(
            `${what}: the OpenPGP library could not be loaded (${(err as Error).message}) -- refusing to install an unverified list`,
        );
    }

    let signature: OpenPgp.Signature;
    try {
        signature = await readDetachedSignature(openpgp, args.signature);
    } catch (err) {
        throw bad(`unreadable: ${(err as Error).message}`);
    }
    const packets = signature.packets.filter((p): p is OpenPgp.SignaturePacket => p instanceof openpgp.SignaturePacket);
    if (packets.length === 0 || packets.length !== signature.packets.length) {
        throw bad('no signature packet');
    }

    const keys = await parseKeySet(openpgp, keySet);
    const signers = packets.map((packet) => {
        const signer = pinnedSignerOf(keys, packet);
        if (signer) return signer;
        if (isWildcard(packet.issuerKeyID)) {
            const fpr = packet.issuerFingerprint;
            throw new ReleaseSignatureError(
                'unknown-key',
                `${what} names no issuer key (wildcard key ID${
                    fpr instanceof Uint8Array && fpr.length > 0 ? `; claimed issuer fingerprint ${hex(fpr)}` : ''
                }), so no pinned ${keySet.label} release key can be matched to it ${REFUSE}`,
            );
        }
        throw new ReleaseSignatureError(
            'unknown-key',
            `${what} names ${claimedIssuerOf(packet)} as its claimed issuer, which is not a pinned ${keySet.label} release key ${REFUSE}`,
        );
    });

    const result = await openpgp.verify({
        message: await openpgp.createMessage({ binary: data }),
        signature,
        verificationKeys: signers.map((s) => s.key),
        format: 'binary',
    });
    // openpgp drops signature types other than binary/text; a packet it
    // dropped was not checked, so it does not count as passing.
    if (result.signatures.length !== packets.length) {
        throw bad('a signature packet is not a document signature');
    }

    let first: VerifiedSignature | undefined;
    // Each signer below is matched on an exact, non-wildcard key ID, so
    // `getKeys` / `getSigningKey` with that ID find exactly that key.
    for (const [i, packet] of packets.entries()) {
        const signer = signers[i]!;
        const created = packet.created;
        if (!(created instanceof Date)) throw bad('the signature has no creation time');
        try {
            await result.signatures[i]!.verified;
        } catch (err) {
            // openpgp checks the bytes first and the key's validity at the
            // signature's creation time second, and reports both the same way.
            // Ask the second question on its own to tell them apart.
            const validity = await signer.key.getSigningKey(packet.issuerKeyID, created).then(
                () => null,
                (e: Error) => e,
            );
            if (validity) {
                throw new ReleaseSignatureError(
                    'key-not-valid',
                    `${what} was signed on ${created.toISOString()} by ${signer.pinned.fingerprint} ` +
                        `(${signer.pinned.owner}), a key that was not valid then (${validity.message}) ${REFUSE}`,
                );
            }
            throw bad((err as Error).message);
        }
        const signingKey = signer.key.getKeys(packet.issuerKeyID)[0]!;
        first ??= {
            fingerprint: signer.pinned.fingerprint.toUpperCase(),
            signingKeyFingerprint: signingKey.getFingerprint().toUpperCase(),
            owner: signer.pinned.owner,
            created,
        };
    }
    return first!;
}
